name: Stock Data Pipeline

on:
  schedule:
    - cron: "30 21 * * 1-5"  # Runs at 2 PM UTC on weekdays (market hours)
  push:
    branches: [ "main" ]    # Optional: Trigger on pushes to main

jobs:
  fetch_and_store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch stock data
        run: |
          python src/main.py  # Runs your yfinance script

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 with versioning
        run: |
          # Upload latest data
          aws s3 cp AAPL_latest_*.csv s3://${{ secrets.AWS_S3_BUCKET }}/latest/

          # Archive old data (timestamped)
          aws s3 cp AAPL_latest_*.csv s3://${{ secrets.AWS_S3_BUCKET }}/historical/$(date +%Y%m%d)/

          # Optional: Clean up local files
          rm *.csv